In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

In [2]:
df_positive = pd.read_csv("/data/private/pdutta/DNABERT_data/Core_Prom_new/TATA/raw_positive.tsv", sep="\t")
df_negative = pd.read_csv("/data/private/pdutta/DNABERT_data/Core_Prom_new/TATA/raw_negative.tsv", sep="\t")

In [5]:
df_positive

,Chromosome,50BP_Start,50BP_End,Strand,TSS,GeneID,gene_type,gene_name,hgnc_id,havana_gene,transcript_id,transcript_type,transcript_name,Sequence,TATA_Box_Positions
0,chr1,30217,30317,+,30267,ENSG00000243485.5,lncRNA,MIR1302-2HG,HGNC:52482,OTTHUMG00000000959.2,ENST00000469289.1,lncRNA,MIR1302-2HG-201,AAAGAAAGAAAAGAGGCTTTTTTAAAAAGTTAAATATATAAAAAGA...,"[30, 36]"
1,chr1,120932,121032,-,120932,ENSG00000238009.6,lncRNA,ENSG00000238009,[nan],OTTHUMG00000001096.2,ENST00000466430.5,lncRNA,ENST00000466430,AATAGATATACAATATATAATATGTAATAGATATATATTATATATA...,"[13, 31, 38, 51, 58]"
2,chr1,157887,157987,-,157887,ENSG00000222623.1,snRNA,RNU6-1100P,HGNC:48063,[nan],ENST00000410691.1,snRNA,RNU6-1100P-201,TATTTACTGAGCTGTTACTAGGTGCCTATAAATAGCATAGATTTTT...,"[0, 26]"
3,chr1,182646,182746,+,182696,ENSG00000279928.2,unprocessed_pseudogene,DDX11L17,HGNC:55080,OTTHUMG00000191962.1,ENST00000624431.2,unprocessed_pseudogene,DDX11L17-201,CCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGG...,[21]
4,chr1,297502,297602,-,297502,ENSG00000228463.10,transcribed_processed_pseudogene,ENSG00000228463,[nan],OTTHUMG00000002552.3,ENST00000424587.7,processed_transcript,ENST00000424587,ATGTAATAGATATACAATATATAATATATAATAGATATATAATATT...,"[17, 24, 35, 45, 58]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8471,chrY,24501505,24501605,-,24501505,ENSG00000232003.2,processed_pseudogene,ZNF736P12Y,HGNC:38431,OTTHUMG00000045107.1,ENST00000443152.1,processed_pseudogene,ZNF736P12Y-201,TTGTCACCTTGTTAATGTGCTTTGTGTAACTAATATTTGTAAAATG...,[29]
8472,chrY,24683607,24683707,+,24683657,ENSG00000226270.3,processed_pseudogene,ZNF736P2Y,HGNC:37727,OTTHUMG00000045110.1,ENST00000416040.1,processed_pseudogene,ZNF736P2Y-201,TGAGTCTAATGAGGGAGAGATTTATAGTCCTTTTATTTTCTTAGCT...,[20]
8473,chrY,24978317,24978417,-,24978317,ENSG00000278602.1,unprocessed_pseudogene,ENSG00000278602,[nan],OTTHUMG00000188109.1,ENST00000616864.1,unprocessed_pseudogene,ENST00000616864,AGAAATTTAAAATATCTATAGTAAATAAATGACATTAATTCTGCAT...,[21]
8474,chrY,25904468,25904568,+,25904518,ENSG00000232914.1,unprocessed_pseudogene,TRAPPC2P4,HGNC:10713,OTTHUMG00000045261.1,ENST00000421750.1,unprocessed_pseudogene,TRAPPC2P4-201,AAAAATATGCACTATTTTTTGCTTCATTAGGAGCCATATATTGAAG...,[34]
8475,chrY,26247334,26247434,+,26247384,ENSG00000251796.1,snoRNA,SNORA70,[nan],[nan],ENST00000515987.1,snoRNA,SNORA70.11-201,CCTATTTCTCTTCCTAATACTATTTGTTTACACCTATAGTTTTTCT...,"[13, 20]"

In [7]:
df_TATA = df_positive[['Chromosome','50BP_Start','50BP_End','Sequence']]
df_TATA = df_TATA.rename(columns={
    '50BP_Start':'Start',
    '50BP_End':'End'
})
df_TATA['Label'] = 1
df_TATA

,Chromosome,Start,End,Sequence,Label
0,chr1,30217,30317,AAAGAAAGAAAAGAGGCTTTTTTAAAAAGTTAAATATATAAAAAGA...,1
1,chr1,120932,121032,AATAGATATACAATATATAATATGTAATAGATATATATTATATATA...,1
2,chr1,157887,157987,TATTTACTGAGCTGTTACTAGGTGCCTATAAATAGCATAGATTTTT...,1
3,chr1,182646,182746,CCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGG...,1
4,chr1,297502,297602,ATGTAATAGATATACAATATATAATATATAATAGATATATAATATT...,1
...,...,...,...,...,...
8471,chrY,24501505,24501605,TTGTCACCTTGTTAATGTGCTTTGTGTAACTAATATTTGTAAAATG...,1
8472,chrY,24683607,24683707,TGAGTCTAATGAGGGAGAGATTTATAGTCCTTTTATTTTCTTAGCT...,1
8473,chrY,24978317,24978417,AGAAATTTAAAATATCTATAGTAAATAAATGACATTAATTCTGCAT...,1
8474,chrY,25904468,25904568,AAAAATATGCACTATTTTTTGCTTCATTAGGAGCCATATATTGAAG...,1
8475,chrY,26247334,26247434,CCTATTTCTCTTCCTAATACTATTTGTTTACACCTATAGTTTTTCT...,1

In [8]:
df_TATA_negative = df_negative[['Chromosome','Start','End','Sequence']]
df_TATA_negative['Label'] = 0
df_TATA_negative

,Chromosome,Start,End,Sequence,Label
0,chr5,26073800,26073900,GACTATACCAAGGCATTTCTACACCTTTCTTTATCATCTGTACATT...,0
1,chr16,7125250,7125350,GTTGTCGTTCAGCCTTTCTAACCTGCAGCATCCTCATTTGTGCAGT...,0
2,chr8,107362200,107362300,TAACAGGCAACGTGCCATGAATACATAAATATGAAAAAGATGCAGT...,0
3,chr10,123781250,123781350,GAGGCAATGTCTGCTCTTCACTTGATTCCCTTCCATATAAATTGAC...,0
4,chr3,149746400,149746500,AGGAGTAGTTTCAGTAGAGAGGGGGTGTATTAGTCCTTTCTCACAC...,0
...,...,...,...,...,...
8495,chr3,105119050,105119150,ACACATAAATATAGTCATCCACTGCCTACGGAAATTTTAGTCAATG...,0
8496,chr10,10642300,10642400,GTCACACCAACCTTCATACTCTCTCTGAATCACTTCTCCAGCACAG...,0
8497,chr18,1045150,1045250,ATACATATATGTAGATTCCATCATATATGGGAACAAAAGTTTCCAT...,0
8498,chr6,51491650,51491750,ACAACATGGGAGAAAGGCAGGCAGAAGCAAGATACCCCATCCACTT...,0
8499,chr9,108426800,108426900,CCTAAAAACAGAAACAGCATTCCACCCAGCAATCCTGTTACTGGAT...,0

In [18]:
def seq2kmer(seq):
    """
    Convert original sequence to kmers
    
    Arguments:
    seq -- str, original sequence.
    k -- int, kmer of length k specified.
    
    Returns:
    kmers -- str, kmers separated by space
    """
    k=6
    kmer = [seq[x:x+k] for x in range(len(seq)+1-k)]
    kmers = " ".join(kmer)
    return kmers

In [25]:
df= pd.concat([df_TATA, df_TATA_negative]).reset_index(drop=True)
df = df.rename(columns={
    'Sequence':'Reference_sequence'
})

In [26]:
df['Sequence'] = df['Reference_sequence'].apply(seq2kmer)

In [27]:
df

,Chromosome,Start,End,Reference_sequence,Label,Sequence
0,chr1,30217,30317,AAAGAAAGAAAAGAGGCTTTTTTAAAAAGTTAAATATATAAAAAGA...,1,AAAGAA AAGAAA AGAAAG GAAAGA AAAGAA AAGAAA AGAA...
1,chr1,120932,121032,AATAGATATACAATATATAATATGTAATAGATATATATTATATATA...,1,AATAGA ATAGAT TAGATA AGATAT GATATA ATATAC TATA...
2,chr1,157887,157987,TATTTACTGAGCTGTTACTAGGTGCCTATAAATAGCATAGATTTTT...,1,TATTTA ATTTAC TTTACT TTACTG TACTGA ACTGAG CTGA...
3,chr1,182646,182746,CCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGG...,1,CCCCTG CCCTGT CCTGTT CTGTTG TGTTGT GTTGTC TTGT...
4,chr1,297502,297602,ATGTAATAGATATACAATATATAATATATAATAGATATATAATATT...,1,ATGTAA TGTAAT GTAATA TAATAG AATAGA ATAGAT TAGA...
...,...,...,...,...,...,...
16971,chr3,105119050,105119150,ACACATAAATATAGTCATCCACTGCCTACGGAAATTTTAGTCAATG...,0,ACACAT CACATA ACATAA CATAAA ATAAAT TAAATA AAAT...
16972,chr10,10642300,10642400,GTCACACCAACCTTCATACTCTCTCTGAATCACTTCTCCAGCACAG...,0,GTCACA TCACAC CACACC ACACCA CACCAA ACCAAC CCAA...
16973,chr18,1045150,1045250,ATACATATATGTAGATTCCATCATATATGGGAACAAAAGTTTCCAT...,0,ATACAT TACATA ACATAT CATATA ATATAT TATATG ATAT...
16974,chr6,51491650,51491750,ACAACATGGGAGAAAGGCAGGCAGAAGCAAGATACCCCATCCACTT...,0,ACAACA CAACAT AACATG ACATGG CATGGG ATGGGA TGGG...
16975,chr9,108426800,108426900,CCTAAAAACAGAAACAGCATTCCACCCAGCAATCCTGTTACTGGAT...,0,CCTAAA CTAAAA TAAAAA AAAAAC AAAACA AAACAG AACA...

In [28]:
train, test = train_test_split(df, test_size=0.20)

In [29]:
train

,Chromosome,Start,End,Reference_sequence,Label,Sequence
5140,chr3,53745778,53745878,GAGAAGCCTGCATTTACTTAACTGCCTGTCTATTTTATACCCAGGG...,1,GAGAAG AGAAGC GAAGCC AAGCCT AGCCTG GCCTGC CCTG...
8185,chrX,38023986,38024086,ATATGTAGAGTTAAACCAAGTTAAATATTTTTTTTTCTACAGAACT...,1,ATATGT TATGTA ATGTAG TGTAGA GTAGAG TAGAGT AGAG...
7507,chr8,19642022,19642122,GCAGAATGGAACTCTGTTTTAGTGCCTATTTAACAAGCCATTTTCC...,1,GCAGAA CAGAAT AGAATG GAATGG AATGGA ATGGAA TGGA...
1555,chr12,12771705,12771805,TGTTTCACTTATACATAAATATACATAGCTATATATATGCAATATA...,1,TGTTTC GTTTCA TTTCAC TTCACT TCACTT CACTTA ACTT...
898,chr10,75601190,75601290,TATGTTTCCCCACATCCTTGGAAATGCAAATCACTTATTTGTCCCA...,1,TATGTT ATGTTT TGTTTC GTTTCC TTTCCC TTCCCC TCCC...
...,...,...,...,...,...,...
10336,chr12,60853250,60853350,TGAATAATTTAGTTTCATTTTATCCTATTGTTTATTAAAATGGTAA...,0,TGAATA GAATAA AATAAT ATAATT TAATTT AATTTA ATTT...
12179,chr17,60789900,60790000,AAATGAAAATTAAGATTTTGTTACATTGTTTTCTAACCTTGAAATG...,0,AAATGA AATGAA ATGAAA TGAAAA GAAAAT AAAATT AAAT...
6938,chr6,135880840,135880940,CATCTCTGGGATTAGAACTATTAGCAAACTTATAATTTTCTTTCCT...,1,CATCTC ATCTCT TCTCTG CTCTGG TCTGGG CTGGGA TGGG...
15313,chr11,35074350,35074450,AAAGTTAAACACATAGCTAACATACGACCCAGTCATTCTATTCTTA...,0,AAAGTT AAGTTA AGTTAA GTTAAA TTAAAC TAAACA AAAC...
7484,chr8,12729387,12729487,TGTTCTTGCCAAGAATAAAAACCACCTTATTTAGAACTAATTCTTT...,1,TGTTCT GTTCTT TTCTTG TCTTGC CTTGCC TTGCCA TGCC...

In [30]:
output_path = "/data/private/pdutta/DNABERT_data/Core_Prom_new/TATA"

In [24]:
train.to_csv(output_path+"/raw_train.tsv", sep="\t", index=False)
test.to_csv(output_path+"/raw_test.tsv", sep="\t", index=False)

In [33]:
train[['Sequence','Label']].to_csv(output_path+ "/train.tsv", sep="\t", index=False)
test[['Sequence','Label']].to_csv(output_path+ "/dev.tsv", sep="\t", index=False)